# edge_ai_pipeline 配置文件
# 修改后重启程序生效，无需重新编译

[capture]
video_device   = /dev/video9
capture_width  = 640
capture_height = 480

[inference]
box_thresh = 0.25
nms_thresh = 0.45

[mqtt]
mqtt_host  = 127.0.0.1
mqtt_port  = 1883
mqtt_topic = edge/detect

[web]
http_port    = 8080
jpeg_quality = 70
